NAME="vantablack"
BAT_THEME="ansi"
FONT_SIZE="12"
WAYBAR_FONT_SIZE="13px"

BG="#0d0d0d"
FG="#ffffff"
ACCENT="#8d8d8d"
SURFACE="#1a1a1a"
CURSOR="#ffffff"
SEL_FG="#0d0d0d"
SEL_BG="#ffffff"
DIM="#4d4d4d"
BORDER_INACTIVE="#333333"
URL="#b0b0b0"

COLOR0="#0d0d0d"
COLOR1="#a4a4a4"
COLOR2="#b6b6b6"
COLOR3="#cecece"
COLOR4="#8d8d8d"
COLOR5="#9b9b9b"
COLOR6="#b0b0b0"
COLOR7="#ececec"
COLOR8="#fdfdfd"
COLOR9="#a4a4a4"
COLOR10="#b6b6b6"
COLOR11="#cecece"
COLOR12="#8d8d8d"
COLOR13="#9b9b9b"
COLOR14="#b0b0b0"
COLOR15="#ffffff"

COLOR_RED="#ffffff"
COLOR_GREEN="#b6b6b6"
COLOR_YELLOW="#cecece"
COLOR_PURPLE="#9b9b9b"
