NAME="carbonfox"
BAT_THEME="base16"
FONT_SIZE="13"
WAYBAR_FONT_SIZE="14px"

BG="#161616"
FG="#f2f4f8"
ACCENT="#78a9ff"
SURFACE="#2a2a2a"
CURSOR="#f2f4f8"
SEL_FG="#f2f4f8"
SEL_BG="#2a2a2a"
DIM="#6e6f70"
BORDER_INACTIVE="#535353"
URL="#25be6a"

COLOR0="#282828"
COLOR1="#ee5396"
COLOR2="#25be6a"
COLOR3="#08bdba"
COLOR4="#78a9ff"
COLOR5="#be95ff"
COLOR6="#33b1ff"
COLOR7="#dfdfe0"
COLOR8="#484848"
COLOR9="#f16da6"
COLOR10="#46c880"
COLOR11="#2dc7c4"
COLOR12="#8cb6ff"
COLOR13="#c8a5ff"
COLOR14="#52bdff"
COLOR15="#e4e4e5"

COLOR_RED="#ee5396"
COLOR_GREEN="#25be6a"
COLOR_YELLOW="#08bdba"
COLOR_PURPLE="#be95ff"
